version: "1"
projects:
- name: WorkFlows
  environments:
  - name: Production
    services:
    - type: web
      name: n8n
      env: docker
      repo: https://github.com/jhoan9/docker-n8n
      plan: free
      region: oregon
      autoDeploy: true